# Generated by Django 5.2.11 on 2026-02-06 02:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_vencimento', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Dívida Ativa'), ('NEGOCIACAO', 'Em Negociação'), ('PAGA', 'Dívida Paga'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('baixado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividas_baixadas', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividas_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to='dividas.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to='dividas.empresa')),
            ],
            options={
                'verbose_name': 'Dívida',
                'verbose_name_plural': 'Dívidas',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoDivida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CADASTRO', 'Cadastro da Dívida'), ('ATUALIZACAO', 'Atualização de Dados'), ('PAGAMENTO_PARCIAL', 'Pagamento Parcial'), ('PAGAMENTO_TOTAL', 'Pagamento Total'), ('NEGOCIACAO', 'Início de Negociação'), ('CANCELAMENTO', 'Cancelamento'), ('REATIVACAO', 'Reativação')], max_length=20)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_atualizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField()),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='dividas.divida')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico da Dívida',
                'verbose_name_plural': 'Históricos das Dívidas',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_empresa', models.BooleanField(default=False)),
                ('data_associacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dividas.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário da Empresa',
                'verbose_name_plural': 'Usuários das Empresas',
            },
        ),
        migrations.AddIndex(
            model_name='divida',
            index=models.Index(fields=['cliente', 'empresa'], name='dividas_div_cliente_7e760a_idx'),
        ),
        migrations.AddIndex(
            model_name='divida',
            index=models.Index(fields=['status', 'data_vencimento'], name='dividas_div_status_38846b_idx'),
        ),
    ]
