# Generated by Django 5.2.11 on 2026-02-06 04:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='historicodivida',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicodivida',
            name='tipo_acao',
            field=models.CharField(choices=[('CADASTRO', 'Cadastro da Dívida'), ('ATUALIZACAO', 'Atualização de Dados'), ('PAGAMENTO_PARCIAL', 'Pagamento Parcial'), ('PAGAMENTO_TOTAL', 'Pagamento Total'), ('NEGOCIACAO', 'Início de Negociação'), ('CANCELAMENTO', 'Cancelamento'), ('REATIVACAO', 'Reativação'), ('STATUS_ALTERADO', 'Status Alterado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='dividas.empresa'),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioempresa',
            unique_together={('usuario', 'empresa')},
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf'], name='dividas_cli_cpf_97cb7f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome_completo'], name='dividas_cli_nome_co_0c576e_idx'),
        ),
        migrations.AddIndex(
            model_name='divida',
            index=models.Index(fields=['data_cadastro'], name='dividas_div_data_ca_373b63_idx'),
        ),
    ]
