# Generated by Django 6.0.2 on 2026-02-07 16:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividas', '0002_alter_cliente_options_alter_historicodivida_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
